name: kalahok_app
description: Kalahok (E-Participation v2.0) Mobile App
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  equatable: ^2.0.5
  flutter_svg: ^1.1.6
  syncfusion_flutter_datepicker: 20.3.59
  flutter_sound_lite: ^8.5.0
  permission_handler: ^10.2.0
  searchable_paginated_dropdown: ^0.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
